# Generated by Django 5.2.15 on 2026-07-06 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SipAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='Doit correspondre à un endpoint déclaré dans asterisk/pjsip.conf', max_length=32, unique=True)),
                ('encrypted_password', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sip_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte SIP',
                'verbose_name_plural': 'Comptes SIP',
            },
        ),
    ]
