# Generated by Django 5.2.15 on 2026-07-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sipaccount',
            options={'verbose_name': 'SIP account', 'verbose_name_plural': 'SIP accounts'},
        ),
        migrations.AlterField(
            model_name='sipaccount',
            name='extension',
            field=models.CharField(help_text='Must match an endpoint declared in asterisk/pjsip.conf', max_length=32, unique=True),
        ),
    ]
