[from-phones]
exten => 004,1,Progress()
exten => 004,n,Dial(PJSIP/004,30)
exten => 004,n,Hangup()

exten => 005,1,Progress()
exten => 005,n,Dial(PJSIP/005,30)
exten => 005,n,Hangup()

exten => 006,1,Progress()
exten => 006,n,Dial(PJSIP/006,30)
exten => 006,n,Hangup()
