[transport-udp]
type     = transport
protocol = udp
bind     = 0.0.0.0:5060

[transport-ws]
type     = transport
protocol = ws
bind     = 0.0.0.0

[ep_browser](!)
type            = endpoint
transport       = transport-ws
context         = from-phones
disallow        = all
allow           = opus,ulaw,alaw
webrtc          = yes
direct_media    = no
rewrite_contact = yes
identify_by     = username
force_rport     = yes
rtp_symmetric   = yes
from_domain     = localhost

[004](ep_browser)
callerid        = "Alice Dupont" <004>
auth            = auth004
aors            = 004

[auth004]
type      = auth
auth_type = userpass
username  = 004
password  = my_password

[004]
type         = aor
max_contacts = 1

[005](ep_browser)
callerid        = "Bob Martin" <005>
auth            = auth005
aors            = 005

[auth005]
type      = auth
auth_type = userpass
username  = 005
password  = my_password

[005]
type         = aor
max_contacts = 1

[006](ep_browser)
callerid        = "Charlie Bernard" <006>
auth            = auth006
aors            = 006

[auth006]
type      = auth
auth_type = userpass
username  = 006
password  = my_password

[006]
type         = aor
max_contacts = 1
